### ISSUE TITLE
Documentation for building and administering servers

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap-Documentation#13]
@gleachkr and I were talking offline about setting up documentation for people who want to a) run their own servers (maybe on their laptops) just to play around, b) people with Haskell skills who want to help with development, c) server admins who are tasked with setting up and running a Carnap server, and d) server admins who have to do things like promote users to instructors, set up LTI integration, and find things in logs. We want:

- [ ] An installing Carnap quick start guide (step-by-step instructions for downloading Carnap to the point where you have your own instance on `localhost` that you can play with). #14 
- [ ] Instructions aimed a developers (including documentation of configuration files, possible build workflows, etc.) #15
- [ ] Instructions aimed at server admins (how to set up a production server; possibly how to run a build/test server and deploying to a production server; info on database configuration; info on doing this on different platforms). #16 #17
- [ ] Instructions for administering a running server. #18
- [ ] Instructions for LTI integration. #19

@lf- already has started some of that:
https://github.com/Carnap/Carnap-Documentation/blob/master/doc/administration.md
https://github.com/Carnap/Carnap-Documentation/blob/master/doc/lti.md
and there's also the Readme at
https://github.com/Carnap/Carnap/blob/master/README.md
but many things are not documented; many things assume knowledge or prerequisites that aren't listed or that can't be expected of the reader (esp. a and c); and there the documentation (I think) gives alternative/conflicting ways of doing things.
